name: Baato JS Geocoder

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    environment: Variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Test Package
        run: echo "Test Done!"
